(() => {
'use strict';
const C = window.PRIVATE_OFFICE_CONFIG || {};
const API = String(C.API_URL || '').replace(/\/$/, '');
const SESSION_KEY = 'private_office_session_v1';
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const state = { session: localStorage.getItem(SESSION_KEY) || '', person: null, file: null };
const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const cleanChat = s => String(s ?? '').replace(/\*\*(.*?)\*\*/g, '$1').replace(/__(.*?)__/g, '$1');
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),3200)}
function show(id){$('#'+id)?.classList.remove('hidden')} function hide(id){$('#'+id)?.classList.add('hidden')}
function formatBytes(n){n=Number(n||0);if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB'}
function when(s){try{const d=new Date(s);return d.toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}catch{return ''}}
async function api(path, opts={}){
  const headers={...(opts.headers||{})}; if(state.session) headers.Authorization=`Bearer ${state.session}`;
  const r=await fetch(API+path,{...opts,headers}); let d=null; const ct=r.headers.get('content-type')||''; if(ct.includes('application/json')){try{d=await r.json()}catch{}}
  if(!r.ok){const e=new Error(d?.error||`Request failed (${r.status})`);e.status=r.status;throw e} return d ?? r;
}
function setSession(token){state.session=token||''; if(token)localStorage.setItem(SESSION_KEY,token);else localStorage.removeItem(SESSION_KEY)}
async function acceptInvite(token){show('inviteLoading');hide('ownerSetupToggle');$('#accessText').textContent='Opening your private invitation…';try{const d=await api('/api/invite/accept',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,device_label:navigator.userAgent.slice(0,100)})});setSession(d.session_token);history.replaceState({},'',location.pathname);await enter()}catch(e){hide('inviteLoading');show('accessError');$('#accessError').textContent=e.message}}
async function enter(){try{const d=await api('/api/me');state.person=d.person;hide('access');show('app');renderPerson();await loadFeed()}catch(e){if(e.status===401){setSession('');showAccess()}else toast(e.message)}}
function showAccess(){show('access');hide('app');hide('inviteLoading');show('ownerSetupToggle');$('#accessText').textContent='Open your private invitation link to enter Private Office.'}
function renderPerson(){const p=state.person||{};const first=(p.name||'').split(' ')[0]||'there';$('#greeting').textContent=`What do you need, ${first}?`;$('#profileName').textContent=p.name||'Private Office';$('#profileRole').textContent=p.role||'';$('#profileInitial').textContent=(p.name||'P').charAt(0).toUpperCase();$('#profileModalName').textContent=p.name||'Private Office';$('#profileModalRole').textContent=p.role==='owner'?'Owner':p.role==='assistant'?'Assistant':'Staff';$('#peopleNav').classList.toggle('hidden',p.role!=='owner')}
function needsRepair(f){return Number(f?.ai_used||0)===0 || /stored safely\. ai classification can be retried later/i.test(String(f?.summary||''))}
function fileActions(f){return `<div class="fileActions">${needsRepair(f)?`<button class="retryFile" data-file-id="${esc(f.id)}">Retry AI</button>`:''}<button class="openFile" data-file-id="${esc(f.id)}">Get file</button></div>`}
function fileCard(f){return `<div class="fileCard"><div class="fileIcon">${esc((f.document_type||'DOC').slice(0,3).toUpperCase())}</div><div class="fileMeta"><b>${esc(f.name||f.title||'Document')}</b><small>${esc([f.category,f.entity_name].filter(Boolean).join(' · ')||f.document_type||'File')}</small>${f.summary?`<p>${esc(f.summary)}</p>`:''}</div>${fileActions(f)}</div>`}
function messageHtml(m){const mine=m.role==='user'&&m.person===state.person?.name;const who=m.role==='assistant'?'Private Office':m.person||'System';return `<article class="msg ${m.role==='assistant'?'assistant':mine?'mine':'other'}"><div class="msgHead"><b>${esc(who)}</b><span>${esc(when(m.created_at))}</span></div>${m.text?`<div class="msgText">${esc(cleanChat(m.text))}</div>`:''}${m.file?fileCard(m.file):''}</article>`}
async function loadFeed(){try{$('#memoryStatus').textContent='Loading memory…';const d=await api('/api/feed');const feed=$('#feed');feed.innerHTML=(d.messages||[]).map(messageHtml).join('')||`<div class="empty"><div class="emptyOrb">✦</div><b>Your office is ready.</b><p>Send a note, question, photo or document. I’ll remember it.</p></div>`;feed.scrollTop=feed.scrollHeight;$('#memoryStatus').textContent='Private and ready';bindFileButtons()}catch(e){$('#memoryStatus').textContent='Connection issue';toast(e.message)}}
function bindFileButtons(){$$('.openFile').forEach(b=>b.onclick=()=>downloadFile(b.dataset.fileId,b));$$('.retryFile').forEach(b=>b.onclick=()=>retryAI(b.dataset.fileId,b))}
async function retryAI(fileId,button){const old=button.textContent;button.textContent='Reading…';button.disabled=true;$('#memoryStatus').textContent='Re-reading file with AI…';try{const d=await api(`/api/files/${encodeURIComponent(fileId)}/repair`,{method:'POST'});toast(d.already_classified?'Already classified':'File reclassified');await loadFeed();if(!$('#libraryModal')?.classList.contains('hidden'))await loadLibrary($('#librarySearch')?.value.trim()||'')}catch(e){toast(e.message);$('#memoryStatus').textContent='Private and ready'}finally{button.textContent=old;button.disabled=false}}
async function downloadFile(fileId,button){const old=button.textContent;button.textContent='Getting…';button.disabled=true;try{const r=await fetch(`${API}/api/files/${encodeURIComponent(fileId)}`,{headers:{Authorization:`Bearer ${state.session}`}});if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.error||'Could not retrieve file')}const blob=await r.blob();const cd=r.headers.get('content-disposition')||'';let name='Private Office file';const m=cd.match(/filename\*=UTF-8''([^;]+)/i);if(m)name=decodeURIComponent(m[1]);const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}catch(e){toast(e.message)}finally{button.textContent=old;button.disabled=false}}
function selectFile(file){if(!file)return;const max=(Number(C.MAX_UPLOAD_MB)||12)*1048576;if(file.size>max)return toast(`Maximum file size is ${C.MAX_UPLOAD_MB||12} MB`);state.file=file;$('#attachmentName').textContent=file.name;$('#attachmentSize').textContent=formatBytes(file.size);show('attachmentPreview')}
function clearFile(){state.file=null;$('#fileInput').value='';hide('attachmentPreview')}
async function send(){const input=$('#messageInput'),text=input.value.trim();if(!text&&!state.file)return;const fd=new FormData();fd.append('text',text);if(state.file)fd.append('file',state.file,state.file.name);$('#sendButton').disabled=true;$('#memoryStatus').textContent=state.file?'Reading and remembering file…':'Remembering…';input.value='';clearFile();try{const d=await api('/api/message',{method:'POST',body:fd});toast(cleanChat(d.reply||'Remembered'));await loadFeed()}catch(e){toast(e.message);$('#memoryStatus').textContent='Private and ready'}finally{$('#sendButton').disabled=false}}
async function loadLibrary(q=''){try{const d=await api('/api/library'+(q?`?q=${encodeURIComponent(q)}`:''));$('#libraryList').innerHTML=(d.files||[]).map(f=>`<div class="listItem"><div><b>${esc(f.stored_name||f.title)}</b><small>${esc([f.category,f.entity_name,f.document_type].filter(Boolean).join(' · '))}</small>${f.summary?`<p>${esc(f.summary)}</p>`:''}</div>${fileActions({...f,name:f.stored_name})}</div>`).join('')||'<div class="emptySmall">Nothing found.</div>';bindFileButtons()}catch(e){toast(e.message)}}
async function loadPeople(){if(state.person?.role!=='owner')return;try{const d=await api('/api/people');$('#peopleList').innerHTML=(d.people||[]).map(p=>`<div class="personRow"><div class="avatarMini">${esc(p.name.charAt(0).toUpperCase())}</div><div><b>${esc(p.name)}</b><small>${esc(p.role)} · ${p.sessions} active device${Number(p.sessions)===1?'':'s'}</small></div>${p.role!=='owner'&&p.active?`<button class="revokePerson" data-id="${esc(p.id)}">Revoke</button>`:'<span class="statusPill">'+(p.active?'Active':'Revoked')+'</span>'}</div>`).join('');$$('.revokePerson').forEach(b=>b.onclick=()=>revokePerson(b.dataset.id))}catch(e){toast(e.message)}}
async function createInvite(e){e.preventDefault();const name=$('#inviteName').value.trim(),role=$('#inviteRole').value;if(!name)return;try{const d=await api('/api/invites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,role,expires_days:30})});$('#inviteUrl').value=d.invite.url;show('newInvite');$('#inviteName').value='';await loadPeople();toast('Private link created')}catch(e){toast(e.message)}}
async function revokePerson(id){if(!confirm('Revoke this person and all of their active sessions?'))return;try{await api('/api/people/revoke',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({person_id:id})});toast('Access revoked');await loadPeople()}catch(e){toast(e.message)}}
function openModal(id){show(id)} function closeModal(id){hide(id)}
async function logout(){try{await api('/api/logout',{method:'POST'})}catch{}setSession('');location.reload()}
function bind(){
  $('#ownerSetupToggle').onclick=()=>{hide('ownerSetupToggle');show('ownerSetup')};
  $('#ownerSetup').onsubmit=async e=>{e.preventDefault();hide('accessError');try{const d=await api('/api/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#setupName').value.trim()||'Owner',setup_key:$('#setupKey').value,device_label:navigator.userAgent.slice(0,100)})});setSession(d.session_token);$('#setupKey').value='';await enter()}catch(err){show('accessError');$('#accessError').textContent=err.message}};
  $('#attachButton').onclick=()=>$('#fileInput').click();$('#navAdd').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>selectFile(e.target.files?.[0]);$('#clearAttachment').onclick=clearFile;$('#sendButton').onclick=send;$('#messageInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};
  $$('[data-quick]').forEach(b=>b.onclick=()=>{$('#messageInput').value=b.dataset.quick;send()});$('#refreshFeed').onclick=loadFeed;
  $$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$('.overlay').forEach(o=>o.onclick=e=>{if(e.target===o)closeModal(o.id)});
  $('[data-nav="memory"]').onclick=()=>{openModal('libraryModal');loadLibrary()};$('#peopleNav').onclick=()=>{openModal('peopleModal');loadPeople()};$('[data-nav="me"]').onclick=()=>openModal('profileModal');$('[data-nav="home"]').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('#profileButton').onclick=()=>openModal('profileModal');
  let st;$('#librarySearch').oninput=e=>{clearTimeout(st);st=setTimeout(()=>loadLibrary(e.target.value.trim()),220)};$('#inviteForm').onsubmit=createInvite;$('#copyInvite').onclick=async()=>{try{await navigator.clipboard.writeText($('#inviteUrl').value);toast('Private link copied')}catch{$('#inviteUrl').select();document.execCommand('copy');toast('Private link copied')}};$('#logoutButton').onclick=logout;
}
async function boot(){bind();if(!API){show('accessError');$('#accessError').textContent='API URL is not configured';return}const invite=new URLSearchParams(location.search).get('invite');if(invite)return acceptInvite(invite);if(state.session)return enter();showAccess();}
boot();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
