(() => {
'use strict';
const API=String(window.PRIVATE_OFFICE_CONFIG?.API_URL||'').replace(/\/$/,'');
const SESSION_KEY='private_office_session_v1';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>{n=Number(n||0);if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;if(n<1073741824)return `${(n/1048576).toFixed(1)} MB`;return `${(n/1073741824).toFixed(2)} GB`};
const when=s=>{try{return new Date(s).toLocaleDateString([],{year:'numeric',month:'short',day:'numeric'})}catch{return''}};
const state={files:[],stats:{},view:localStorage.getItem('po_file_view')||'grid',folder:'',query:'',category:'',type:'',uploader:'',status:'',sort:'newest',canDelete:false,canOrganize:false,ready:false};
function token(){return localStorage.getItem(SESSION_KEY)||''}
async function api(path,opts={}){const h={...(opts.headers||{}),Authorization:`Bearer ${token()}`};const r=await fetch(API+path,{...opts,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),3300)}
function icon(f){const m=String(f.mime||'');const e=(f.stored_name||'').split('.').pop().toUpperCase();if(m.startsWith('image/'))return'IMG';if(m.includes('pdf'))return'PDF';if(/sheet|excel/.test(m)||/XLSX?|CSV/.test(e))return'XLS';if(/word/.test(m)||/DOCX?/.test(e))return'DOC';return String(f.document_type||e||'FILE').slice(0,3).toUpperCase()}
function allFolders(){return new Set(state.files.map(f=>f.folder_path).filter(Boolean)).size}
function shell(){const mount=$('#workspaceMount');if(!mount)return;mount.innerHTML=`
  <div class="wsHero">
    <div><span class="wsEyebrow">PRIVATE OFFICE LIBRARY</span><h3>Everything has a place.</h3><p>Search, browse, visualize and organize the originals remembered by your office.</p></div>
    <div class="wsHeroActions"><button id="wsAdd" class="wsButton wsPrimary">＋ Add file</button><button id="wsOrganize" class="wsButton">✦ Organize</button><button id="wsDeep" class="wsButton wsGhost">Deep AI scan</button></div>
  </div>
  <div class="wsStats" id="wsStats"></div>
  <div class="wsToolbar">
    <label class="wsSearch"><span>⌕</span><input id="wsSearch" placeholder="Search filenames, summaries, companies, properties…"></label>
    <div class="wsViews" aria-label="File view"><button data-view="grid" title="Grid view">▦</button><button data-view="list" title="List view">☷</button><button data-view="chart" title="Chart view">▥</button><button data-view="bubbles" title="Bubble view">◉</button></div>
  </div>
  <div class="wsFilters">
    <select id="wsSort" aria-label="Sort files"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name A–Z</option><option value="size">Largest first</option><option value="category">Category</option></select>
    <select id="wsCategory" aria-label="Filter by category"><option value="">All categories</option></select>
    <select id="wsType" aria-label="Filter by type"><option value="">All types</option></select>
    <select id="wsUploader" aria-label="Filter by uploader"><option value="">Everyone</option></select>
    <select id="wsStatus" aria-label="Filter by AI status"><option value="">All files</option><option value="ready">AI organized</option><option value="review">Needs AI review</option></select>
  </div>
  <div class="wsBreadcrumb" id="wsBreadcrumb"></div>
  <div class="wsLayout"><aside class="wsFolders" id="wsFolders"></aside><section class="wsMain"><div id="wsReport"></div><div id="wsResults"></div></section></div>
  <div id="wsConfirm" class="wsConfirm hidden"></div>`;
  bind();state.ready=true;
}
function bind(){
  $('#wsSearch').oninput=e=>{state.query=e.target.value.trim().toLowerCase();render()};
  $('#wsSort').onchange=e=>{state.sort=e.target.value;render()};
  $('#wsCategory').onchange=e=>{state.category=e.target.value;render()};
  $('#wsType').onchange=e=>{state.type=e.target.value;render()};
  $('#wsUploader').onchange=e=>{state.uploader=e.target.value;render()};
  $('#wsStatus').onchange=e=>{state.status=e.target.value;render()};
  document.querySelectorAll('.wsViews button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;localStorage.setItem('po_file_view',state.view);render()});
  $('#wsAdd').onclick=()=>{$('#libraryModal')?.classList.add('hidden');$('#fileInput')?.click()};
  $('#wsOrganize').onclick=()=>organize(false);
  $('#wsDeep').onclick=()=>confirmBox('Deep AI scan','Re-read uncertain and already-classified files with AI. This can improve filing, but uses more AI tokens.','Run deep scan',()=>organize(true));
}
function setOptions(id,items,label){const el=$(id);if(!el)return;const old=el.value;el.innerHTML=`<option value="">${label}</option>`+[...items].sort((a,b)=>a.localeCompare(b)).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');el.value=old}
async function load(){if(!state.ready)shell();const mount=$('#workspaceMount');mount?.classList.add('loading');try{const d=await api('/api/workspace');state.files=d.files||[];state.stats=d.stats||{};state.canDelete=!!d.can_delete;state.canOrganize=!!d.can_organize;setOptions('#wsCategory',new Set(state.files.map(f=>f.category||'Other')),'All categories');setOptions('#wsType',new Set(state.files.map(f=>f.document_type||'Documents')),'All types');setOptions('#wsUploader',new Set(state.files.map(f=>f.created_by_name).filter(Boolean)),'Everyone');$('#wsOrganize').classList.toggle('hidden',!state.canOrganize);$('#wsDeep').classList.toggle('hidden',!state.canOrganize);render()}catch(e){toast(e.message);$('#wsResults').innerHTML=`<div class="wsEmpty">Could not load your file workspace.</div>`}finally{mount?.classList.remove('loading')}}
function filtered(){let a=state.files.filter(f=>{if(state.folder&&!String(f.folder_path||'').startsWith(state.folder))return false;if(state.category&&(f.category||'Other')!==state.category)return false;if(state.type&&(f.document_type||'Documents')!==state.type)return false;if(state.uploader&&f.created_by_name!==state.uploader)return false;if(state.status==='ready'&&!Number(f.ai_used))return false;if(state.status==='review'&&Number(f.ai_used))return false;if(state.query){const h=[f.stored_name,f.original_name,f.title,f.summary,f.search_text,f.category,f.document_type,f.entity_name,f.created_by_name,f.folder_path].filter(Boolean).join(' ').toLowerCase();if(!h.includes(state.query))return false}return true});
  const s=state.sort;a.sort((x,y)=>s==='oldest'?String(x.created_at).localeCompare(String(y.created_at)):s==='name'?String(x.stored_name).localeCompare(String(y.stored_name)):s==='size'?Number(y.size)-Number(x.size):s==='category'?String(x.category).localeCompare(String(y.category)):String(y.created_at).localeCompare(String(x.created_at)));return a}
function render(){if(!state.ready)return;const files=filtered();renderStats(files);renderFolders();renderBreadcrumb(files);document.querySelectorAll('.wsViews button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));const r=$('#wsResults');if(!files.length){r.innerHTML=`<div class="wsEmpty"><div>⌕</div><b>No files here.</b><span>Try another folder or filter.</span></div>`;return}if(state.view==='list')r.innerHTML=listView(files);else if(state.view==='chart')r.innerHTML=chartView(files);else if(state.view==='bubbles')r.innerHTML=bubbleView(files);else r.innerHTML=gridView(files);bindResultActions()}
function renderStats(files){const size=files.reduce((n,f)=>n+Number(f.size||0),0),needs=files.filter(f=>!Number(f.ai_used)).length;$('#wsStats').innerHTML=`<div><b>${files.length}</b><span>Files shown</span></div><div><b>${allFolders()}</b><span>Folders</span></div><div><b>${fmt(size)}</b><span>Storage shown</span></div><div class="${needs?'attention':''}"><b>${needs}</b><span>Need AI review</span></div>`}
function renderBreadcrumb(files){const b=$('#wsBreadcrumb');const parts=state.folder?state.folder.split('/'):[];let acc='';b.innerHTML=`<button data-folder="">All files</button>`+parts.map(p=>{acc=acc?`${acc}/${p}`:p;return`<span>›</span><button data-folder="${esc(acc)}">${esc(p)}</button>`}).join('')+`<em>${files.length} item${files.length===1?'':'s'}</em>`;b.querySelectorAll('button').forEach(x=>x.onclick=()=>{state.folder=x.dataset.folder||'';render()})}
function folderTree(){const root={count:0,children:new Map()};for(const f of state.files){root.count++;let node=root;for(const p of f.folder_parts||[]){if(!node.children.has(p))node.children.set(p,{count:0,children:new Map()});node=node.children.get(p);node.count++}}return root}
function renderFolders(){const root=folderTree(),box=$('#wsFolders');const walk=(node,prefix='',depth=0)=>[...node.children.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([name,n])=>{const path=prefix?`${prefix}/${name}`:name;return`<button class="wsFolder ${state.folder===path?'active':''}" data-folder="${esc(path)}" style="--depth:${depth}"><span>${depth?'⌞':'▰'}</span><b>${esc(name)}</b><em>${n.count}</em></button>${depth<2?walk(n,path,depth+1):''}`}).join('');box.innerHTML=`<button class="wsFolder ${!state.folder?'active':''}" data-folder=""><span>⌂</span><b>All files</b><em>${root.count}</em></button>${walk(root)}`;box.querySelectorAll('.wsFolder').forEach(x=>x.onclick=()=>{state.folder=x.dataset.folder||'';render()})}
function actions(f){return`<div class="wsFileActions"><button class="wsDownload" data-id="${esc(f.id)}" title="Download original">↓ <span>Download</span></button>${!Number(f.ai_used)?`<button class="wsRetry" data-id="${esc(f.id)}" title="Retry AI filing">✦</button>`:''}${state.canDelete?`<button class="wsDelete" data-id="${esc(f.id)}" title="Delete permanently">×</button>`:''}</div>`}
function gridView(files){return`<div class="wsGrid">${files.map(f=>`<article class="wsCard"><div class="wsCardTop"><div class="wsDocIcon">${esc(icon(f))}</div>${actions(f)}</div><div class="wsFolderLine">${esc(f.folder_path||'Other')}</div><h4>${esc(f.stored_name||f.title||'Document')}</h4><p>${esc(f.summary||'No summary yet.')}</p><div class="wsMeta"><span>${fmt(f.size)}</span><span>${when(f.created_at)}</span>${f.created_by_name?`<span>${esc(f.created_by_name)}</span>`:''}</div></article>`).join('')}</div>`}
function listView(files){return`<div class="wsListHead"><span>Name</span><span>Folder</span><span>Size</span><span>Added</span><span></span></div><div class="wsFileList">${files.map(f=>`<article class="wsRow"><div class="wsName"><div class="wsDocIcon small">${esc(icon(f))}</div><div><b>${esc(f.stored_name||f.title||'Document')}</b><small>${esc(f.document_type||'File')}${f.created_by_name?` · ${esc(f.created_by_name)}`:''}</small></div></div><div class="wsPath">${esc(f.folder_path||'Other')}</div><div>${fmt(f.size)}</div><div>${when(f.created_at)}</div>${actions(f)}</article>`).join('')}</div>`}
function group(files,key){const m=new Map();for(const f of files){const k=key(f)||'Other',v=m.get(k)||{name:k,count:0,size:0};v.count++;v.size+=Number(f.size||0);m.set(k,v)}return[...m.values()].sort((a,b)=>b.count-a.count)}
function chartView(files){const g=group(files,f=>f.category||'Other'),max=Math.max(...g.map(x=>x.count),1);return`<div class="wsVisualIntro"><b>Files by category</b><span>Click a bar to filter the workspace.</span></div><div class="wsChart">${g.map(x=>`<button data-category="${esc(x.name)}"><div><b>${esc(x.name)}</b><span>${x.count} files · ${fmt(x.size)}</span></div><i><em style="width:${Math.max(5,x.count/max*100)}%"></em></i><strong>${x.count}</strong></button>`).join('')}</div>`}
function bubbleView(files){const g=group(files,f=>f.entity_name||f.category||'Other'),max=Math.max(...g.map(x=>x.count),1);return`<div class="wsVisualIntro"><b>Office memory map</b><span>Entities and categories grow with the number of remembered files.</span></div><div class="wsBubbles">${g.map(x=>{const s=Math.round(84+Math.sqrt(x.count/max)*95);return`<button style="--bubble:${s}px" data-bubble="${esc(x.name)}"><b>${esc(x.name)}</b><span>${x.count}</span></button>`}).join('')}</div>`}
function bindResultActions(){document.querySelectorAll('.wsDownload').forEach(b=>b.onclick=()=>download(state.files.find(f=>f.id===b.dataset.id),b));document.querySelectorAll('.wsDelete').forEach(b=>b.onclick=()=>{const f=state.files.find(x=>x.id===b.dataset.id);confirmBox('Delete file',`Permanently remove “${f?.stored_name||'this file'}” from Private Office and R2 storage?`,'Delete permanently',()=>removeFile(f))});document.querySelectorAll('.wsRetry').forEach(b=>b.onclick=()=>retry(b.dataset.id,b));document.querySelectorAll('.wsChart button').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;$('#wsCategory').value=state.category;state.view='grid';render()});document.querySelectorAll('.wsBubbles button').forEach(b=>b.onclick=()=>{const name=b.dataset.bubble;const entity=state.files.find(f=>f.entity_name===name);if(entity){state.folder=(entity.folder_parts||[]).slice(0,2).join('/')}else{state.category=name;$('#wsCategory').value=name}state.view='grid';render()})}
async function download(f,b){if(!f)return;const old=b.innerHTML;b.disabled=true;b.textContent='Getting…';try{const r=await fetch(`${API}/api/files/${encodeURIComponent(f.id)}`,{headers:{Authorization:`Bearer ${token()}`}});if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.error||'Could not retrieve file')}const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=f.stored_name||f.original_name||'Document';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}catch(e){toast(e.message)}finally{b.disabled=false;b.innerHTML=old}}
async function retry(id,b){const old=b.textContent;b.textContent='…';b.disabled=true;try{await api(`/api/files/${encodeURIComponent(id)}/repair`,{method:'POST'});toast('AI filing updated');await load()}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent=old}}
async function removeFile(f){if(!f)return;try{await api(`/api/files/${encodeURIComponent(f.id)}`,{method:'DELETE'});toast('File deleted');closeConfirm();await load();$('#refreshFeed')?.click()}catch(e){toast(e.message)}}
async function organize(deep){closeConfirm();const a=deep?$('#wsDeep'):$('#wsOrganize'),old=a.textContent;a.disabled=true;a.textContent=deep?'Scanning…':'Organizing…';$('#wsReport').innerHTML=`<div class="wsProgress"><span></span><div><b>${deep?'Deep AI scan':'Organizing your office'}</b><small>Checking folders, names and filing metadata…</small></div></div>`;try{const d=await api('/api/organize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deep,max_ai:deep?20:8})});const x=d.report||{};$('#wsReport').innerHTML=`<div class="wsReport"><button class="wsReportClose">×</button><b>Office organized.</b><div><span><strong>${x.scanned||0}</strong> scanned</span><span><strong>${x.moved||0}</strong> moved</span><span><strong>${x.renamed||0}</strong> renamed</span><span><strong>${x.reclassified||0}</strong> reclassified</span><span><strong>${x.ai_reads||0}</strong> AI reads</span></div>${x.examples?.length?`<ul>${x.examples.slice(0,5).map(e=>`<li><b>${esc(e.to)}</b><small>${esc(e.folder)}</small></li>`).join('')}</ul>`:''}</div>`;$('#wsReport .wsReportClose').onclick=()=>$('#wsReport').innerHTML='';await load();toast('Private Office organized')}catch(e){toast(e.message);$('#wsReport').innerHTML=''}finally{a.disabled=false;a.textContent=old}}
function confirmBox(title,body,action,go){const c=$('#wsConfirm');c.classList.remove('hidden');c.innerHTML=`<div class="wsConfirmCard"><div class="wsConfirmIcon">!</div><h4>${esc(title)}</h4><p>${esc(body)}</p><div><button id="wsCancel" class="wsButton">Cancel</button><button id="wsConfirmGo" class="wsButton wsDanger">${esc(action)}</button></div></div>`;$('#wsCancel').onclick=closeConfirm;$('#wsConfirmGo').onclick=go;c.onclick=e=>{if(e.target===c)closeConfirm()}}
function closeConfirm(){$('#wsConfirm')?.classList.add('hidden')}
async function open(){if(!state.ready)shell();await load()}
window.PrivateOfficeWorkspace={open,refresh:load};
const modal=$('#libraryModal');if(modal)new MutationObserver(()=>{if(!modal.classList.contains('hidden'))setTimeout(open,0)}).observe(modal,{attributes:true,attributeFilter:['class']});
document.addEventListener('DOMContentLoaded',()=>{if(!state.ready&&$('#workspaceMount'))shell()});
})();