import{ensure,auth,role,session,message,hash,token,uid,now,plusDays,INVITE_DAYS}from'./db.js';
import{classify,answer}from'./ai.js';
const MAX=12*1024*1024;
const safe=s=>String(s||'Document').replace(/[\\/:*?"<>|\u0000-\u001F]/g,' ').replace(/\s+/g,' ').trim().slice(0,120)||'Document';
const ext=n=>(String(n||'').match(/(\.[A-Za-z0-9]{1,8})$/)||['',''])[1].toLowerCase();
const base=n=>ext(n)?String(n).slice(0,-ext(n).length):String(n||'Document');
const filename=(orig,want)=>`${safe(base(want||orig)).replace(/^[-_. ]+|[-_. ]+$/g,'').slice(0,105)||'Document'}${ext(orig)}`;
const J=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8',...h}});
const origins=e=>String(e.APP_ORIGINS||'https://kingamada.github.io').split(',').map(x=>x.trim().replace(/\/$/,'')).filter(Boolean);
const cors=(r,e)=>{const o=(r.headers.get('Origin')||'').replace(/\/$/,'');const a=origins(e);return{'Access-Control-Allow-Origin':a.includes(o)?o:a[0]||'null','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin'}};
const wrap=(res,r,e)=>{const h=new Headers(res.headers);for(const[k,v]of Object.entries(cors(r,e)))h.set(k,v);return new Response(res.body,{status:res.status,headers:h})};
const question=t=>/\?$/.test(String(t).trim())||/^(what|where|when|who|which|how|why|find|show|tell|do i|did i|have i|is there|are there|can you|give me|bring me)\b/i.test(String(t).trim());
async function memory(env,user,q){const stop=new Set(['what','where','when','who','which','how','why','find','show','tell','give','bring','can','could','would','should','do','did','does','have','has','had','is','are','was','were','me','my','i','the','a','an','about','of','to','in','on','for','from','with','documents','document','files','file','records','record','memory','recent','latest','today','please']);const terms=[...new Set(String(q||'').toLowerCase().match(/[a-z0-9]{2,}/g)||[])].filter(x=>!stop.has(x)).slice(0,8);const like=terms.length?`%${terms[terms.length-1]}%`:'%';const files=(await env.DB.prepare(`SELECT id,stored_name,title,category,document_type,summary,search_text,entity_name,document_date,expiry_date,created_by FROM files WHERE (stored_name LIKE ? OR title LIKE ? OR summary LIKE ? OR search_text LIKE ? OR entity_name LIKE ?) ${user.role==='staff'?'AND created_by=?':''} ORDER BY created_at DESC LIMIT 8`).bind(...(user.role==='staff'?[like,like,like,like,like,user.person_id]:[like,like,like,like,like])).all()).results||[];const msgs=(await env.DB.prepare(`SELECT m.text,m.created_at,m.person_id,p.name FROM messages m LEFT JOIN people p ON p.id=m.person_id WHERE m.text LIKE ? ${user.role==='staff'?'AND m.person_id=?':''} ORDER BY m.created_at DESC LIMIT 8`).bind(...(user.role==='staff'?[like,user.person_id]:[like])).all()).results||[];return[...files.map(x=>({kind:'file',...x})),...msgs.map(x=>({kind:'message',text:x.text,created_at:x.created_at,person:x.name||'Private Office'}))].slice(0,10)}
async function fileObj(env,f){return f?{id:f.id,name:f.stored_name,original_name:f.original_name,mime:f.mime,size:f.size,category:f.category,document_type:f.document_type,title:f.title,summary:f.summary,entity_name:f.entity_name,created_at:f.created_at}:null}
async function bootstrap(r,e){if(!e.SETUP_KEY)return J({error:'SETUP_KEY secret is not configured'},503);const b=await r.json();if(String(b.setup_key||'')!==String(e.SETUP_KEY))return J({error:'Invalid setup key'},403);if(await e.DB.prepare("SELECT id FROM people WHERE role='owner' AND active=1 LIMIT 1").first())return J({error:'Owner access already exists'},409);const pid=uid(),t=now(),name=safe(b.name||'Owner');await e.DB.prepare("INSERT INTO people(id,name,role,active,created_at) VALUES(?,?,'owner',1,?)").bind(pid,name,t).run();const s=await session(e,pid,b.device_label||'Owner device');await message(e,{role:'system',text:`${name} created Private Office.`});return J({session_token:s,person:{id:pid,name,role:'owner'}})}
async function acceptInvite(r,e){const b=await r.json(),h=await hash(b.token||'');const x=await e.DB.prepare(`SELECT i.id,i.person_id,i.expires_at,i.revoked_at,p.name,p.role,p.active FROM invites i JOIN people p ON p.id=i.person_id WHERE i.token_hash=? LIMIT 1`).bind(h).first();if(!x||x.revoked_at||!x.active||(x.expires_at&&Date.parse(x.expires_at)<=Date.now()))return J({error:'This private link is invalid, expired or revoked'},403);const s=await session(e,x.person_id,b.device_label||'Private Office device');await e.DB.prepare('UPDATE invites SET use_count=use_count+1 WHERE id=?').bind(x.id).run();return J({session_token:s,person:{id:x.person_id,name:x.name,role:x.role}})}
async function feed(e,u){const w=u.role==='staff'?'WHERE (m.person_id=? OR m.visible_to_person_id=?)':'';const st=e.DB.prepare(`SELECT m.id,m.role,m.text,m.created_at,m.person_id,m.file_id,p.name person_name,f.stored_name,f.original_name,f.mime,f.size,f.category,f.document_type,f.title,f.summary,f.entity_name,f.created_at file_created_at FROM messages m LEFT JOIN people p ON p.id=m.person_id LEFT JOIN files f ON f.id=m.file_id ${w} ORDER BY m.created_at DESC LIMIT 120`);const rows=(u.role==='staff'?await st.bind(u.person_id,u.person_id).all():await st.all()).results||[];return J({messages:rows.reverse().map(x=>({id:x.id,role:x.role,text:x.text,created_at:x.created_at,person:x.person_name||(x.role==='assistant'?'Private Office':'System'),file:x.file_id?{id:x.file_id,name:x.stored_name,original_name:x.original_name,mime:x.mime,size:x.size,category:x.category,document_type:x.document_type,title:x.title,summary:x.summary,entity_name:x.entity_name,created_at:x.file_created_at}:null}))})}
async function send(r,e,u){const fd=await r.formData(),txt=String(fd.get('text')||'').trim().slice(0,30000),up=fd.get('file');if(!txt&&!(up instanceof File&&up.size))return J({error:'Write a message or attach a file'},400);let f=null,fid=null,dup=false;if(up instanceof File&&up.size){if(up.size>MAX)return J({error:'File is too large. Maximum is 12 MB.'},413);const bytes=await up.arrayBuffer(),sha=await hash(bytes);f=await e.DB.prepare('SELECT * FROM files WHERE sha256=? LIMIT 1').bind(sha).first();if(f){fid=f.id;dup=true}else{let c;try{c=await classify(e,bytes,up)}catch{c={suggested_filename:up.name,document_type:'Document',category:'Other',title:base(up.name),summary:'Stored safely. AI classification can be retried later.',search_text:`${up.name} ${txt}`,entity_name:null,document_date:null,expiry_date:null}}fid=uid();const stored=filename(up.name,c.suggested_filename||c.title||up.name),cat=safe(c.category||'Other'),ent=c.entity_name?safe(c.entity_name):'',key=`${cat}/${ent?ent+'/':''}${new Date().toISOString().slice(0,10)}/${fid}-${stored}`;await e.FILES.put(key,bytes,{httpMetadata:{contentType:up.type||'application/octet-stream'},customMetadata:{original_name:safe(up.name),uploaded_by:u.person_id}});const t=now();await e.DB.prepare(`INSERT INTO files(id,r2_key,original_name,stored_name,mime,size,sha256,category,document_type,title,summary,search_text,entity_name,document_date,expiry_date,created_by,created_at,ai_used) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(fid,key,safe(up.name),stored,up.type||'application/octet-stream',up.size,sha,c.category||'Other',c.document_type||'Document',c.title||base(up.name),c.summary||'',c.search_text||`${up.name} ${txt}`,c.entity_name||null,c.document_date||null,c.expiry_date||null,u.person_id,t,c.summary?.startsWith('Stored safely')?0:1).run();f=await e.DB.prepare('SELECT * FROM files WHERE id=?').bind(fid).first()}}let reply;if(f)reply=dup?`Remembered. This is the same file already stored as “${f.stored_name}”. I linked this new message to it.`:`Remembered. I filed it as “${f.stored_name}” under ${f.category||'Other'}${f.entity_name?` → ${f.entity_name}`:''}.`;else if(question(txt))reply=await answer(e,txt,await memory(e,u,txt));else reply='Remembered.';const m=await message(e,{personId:u.person_id,role:'user',text:txt,fileId:fid});await message(e,{role:'assistant',text:reply,visibleTo:u.role==='staff'?u.person_id:null,replyTo:m.id});return J({ok:true,reply,file:await fileObj(e,f)})}
async function library(e,u,url){const q=(url.searchParams.get('q')||'').trim(),clauses=[],b=[];if(u.role==='staff'){clauses.push('created_by=?');b.push(u.person_id)}if(q){const x=`%${q}%`;clauses.push('(stored_name LIKE ? OR title LIKE ? OR summary LIKE ? OR entity_name LIKE ? OR category LIKE ?)');b.push(x,x,x,x,x)}let sql='SELECT id,original_name,stored_name,mime,size,category,document_type,title,summary,entity_name,created_at,created_by FROM files';if(clauses.length)sql+=' WHERE '+clauses.join(' AND ');sql+=' ORDER BY created_at DESC LIMIT 150';return J({files:(await e.DB.prepare(sql).bind(...b).all()).results||[]})}
async function download(e,u,id){const f=await e.DB.prepare('SELECT * FROM files WHERE id=?').bind(id).first();if(!f)return J({error:'File not found'},404);if(u.role==='staff'&&f.created_by!==u.person_id)return J({error:'Not authorized for this file'},403);const o=await e.FILES.get(f.r2_key);if(!o)return J({error:'Stored object is missing'},404);const h=new Headers();o.writeHttpMetadata(h);h.set('Content-Type',f.mime||h.get('Content-Type')||'application/octet-stream');h.set('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(f.stored_name)}`);h.set('Cache-Control','private, no-store');return new Response(o.body,{headers:h})}
async function people(e,u){role(u,['owner']);const t=now();return J({people:(await e.DB.prepare(`SELECT p.id,p.name,p.role,p.active,p.created_at,(SELECT COUNT(*) FROM sessions s WHERE s.person_id=p.id AND s.revoked_at IS NULL AND s.expires_at>?) sessions FROM people p ORDER BY p.created_at`).bind(t).all()).results||[]})}
async function invite(r,e,u){role(u,['owner']);const b=await r.json(),rr=['assistant','staff'].includes(b.role)?b.role:'staff',name=safe(b.name||'Staff'),pid=uid(),iid=uid(),raw=token(32),t=now();await e.DB.prepare('INSERT INTO people(id,name,role,active,created_at) VALUES(?,?,?,1,?)').bind(pid,name,rr,t).run();await e.DB.prepare('INSERT INTO invites(id,person_id,token_hash,created_by,created_at,expires_at) VALUES(?,?,?,?,?,?)').bind(iid,pid,await hash(raw),u.person_id,t,plusDays(Number(b.expires_days||INVITE_DAYS))).run();const base=String(e.APP_URL||'https://kingamada.github.io/private-office/').replace(/\?.*$/,'');return J({invite:{id:iid,person_id:pid,name,role:rr,url:`${base}?invite=${encodeURIComponent(raw)}`}})}
async function revoke(r,e,u){role(u,['owner']);const b=await r.json(),pid=String(b.person_id||'');if(!pid||pid===u.person_id)return J({error:'You cannot revoke your own owner session here'},400);const t=now();await e.DB.batch([e.DB.prepare('UPDATE people SET active=0 WHERE id=?').bind(pid),e.DB.prepare('UPDATE sessions SET revoked_at=? WHERE person_id=? AND revoked_at IS NULL').bind(t,pid),e.DB.prepare('UPDATE invites SET revoked_at=? WHERE person_id=? AND revoked_at IS NULL').bind(t,pid)]);return J({ok:true})}
async function route(r,e){await ensure(e);const u=new URL(r.url),p=u.pathname;if(r.method==='GET'&&(p==='/'||p==='/api/health'))return J({ok:true,service:'Private Office',storage:!!e.FILES,database:!!e.DB});if(r.method==='POST'&&p==='/api/bootstrap')return bootstrap(r,e);if(r.method==='POST'&&p==='/api/invite/accept')return acceptInvite(r,e);const me=await auth(r,e);if(!me)return J({error:'Private session required'},401);if(r.method==='GET'&&p==='/api/me')return J({person:{id:me.person_id,name:me.name,role:me.role}});if(r.method==='GET'&&p==='/api/feed')return feed(e,me);if(r.method==='POST'&&p==='/api/message')return send(r,e,me);if(r.method==='GET'&&p==='/api/library')return library(e,me,u);if(r.method==='GET'&&p.startsWith('/api/files/'))return download(e,me,decodeURIComponent(p.slice(11)));if(r.method==='GET'&&p==='/api/people')return people(e,me);if(r.method==='POST'&&p==='/api/invites')return invite(r,e,me);if(r.method==='POST'&&p==='/api/people/revoke')return revoke(r,e,me);if(r.method==='POST'&&p==='/api/logout'){await e.DB.prepare('UPDATE sessions SET revoked_at=? WHERE id=?').bind(now(),me.session_id).run();return J({ok:true})}return J({error:'Not found'},404)}
export default{async fetch(r,e){if(r.method==='OPTIONS')return new Response(null,{status:204,headers:cors(r,e)});try{return wrap(await route(r,e),r,e)}catch(x){return wrap(J({error:x?.message||'Private Office error'},x?.status||500),r,e)}}};
