const OPENAI='https://api.openai.com/v1';
let jwksCache={at:0,keys:[]};
function allowedOrigins(env){return String(env.APP_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean)}
function originAllowed(origin,env){return allowedOrigins(env).includes(origin)}
function cors(origin,env){const ok=originAllowed(origin,env);return {'Access-Control-Allow-Origin':ok?origin:'null','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Vary':'Origin','Content-Type':'application/json'} }
function json(data,status,origin,env){return new Response(JSON.stringify(data),{status,headers:cors(origin,env)})}
function b64url(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function parseJwt(t){const [h,p,s]=t.split('.');if(!h||!p||!s)throw new Error('Malformed identity token');return {header:JSON.parse(new TextDecoder().decode(b64url(h))),payload:JSON.parse(new TextDecoder().decode(b64url(p))),sig:b64url(s),data:new TextEncoder().encode(`${h}.${p}`)}}
async function jwks(){if(Date.now()-jwksCache.at<3_000_000&&jwksCache.keys.length)return jwksCache.keys;const r=await fetch('https://www.googleapis.com/oauth2/v3/certs');if(!r.ok)throw new Error('Could not load Google signing keys');const d=await r.json();jwksCache={at:Date.now(),keys:d.keys||[]};return jwksCache.keys}
async function verifyGoogle(token,env){const j=parseJwt(token),keys=await jwks(),jwk=keys.find(k=>k.kid===j.header.kid);if(!jwk)throw new Error('Unknown Google signing key');const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const valid=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,j.sig,j.data);if(!valid)throw new Error('Invalid Google signature');const p=j.payload,now=Math.floor(Date.now()/1000);if(!['https://accounts.google.com','accounts.google.com'].includes(p.iss)||p.aud!==env.GOOGLE_CLIENT_ID||Number(p.exp)<now)throw new Error('Expired or invalid Google identity');if(!(p.email_verified===true||p.email_verified==='true'))throw new Error('Google email is not verified');const allowed=String(env.ALLOWED_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(allowed.length&&!allowed.includes(String(p.email||'').toLowerCase()))throw new Error('This Google account is not authorized');return p}
async function safetyId(email){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(email||'private-office')));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,32)}
function outputText(d){if(typeof d.output_text==='string')return d.output_text;for(const item of d.output||[])for(const c of item.content||[])if(c.type==='output_text'&&c.text)return c.text;return ''}
async function openai(path,env,opts={}){const r=await fetch(OPENAI+path,{...opts,headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`,...(opts.headers||{})}});if(!r.ok){let detail='';try{detail=(await r.json())?.error?.message||''}catch{}throw new Error(detail||`OpenAI request failed (${r.status})`)}return r}
const schema={type:'object',additionalProperties:false,properties:{document_type:{type:'string'},category:{type:'string',enum:['Properties','Companies','Banking','Personal','Legal','Vehicles','Insurance','Investments','Taxes','Other']},title:{type:'string'},summary:{type:'string'},search_text:{type:'string'},document_date:{type:['string','null']},expiry_date:{type:['string','null']},linked_entity_type:{type:['string','null'],enum:['property','company','person','banking','vehicle','investment','legal','insurance','tax','other',null]},linked_entity_name:{type:['string','null']},parties:{type:'array',items:{type:'string'}},tags:{type:'array',items:{type:'string'}},sensitivity:{type:'string',enum:['normal','sensitive','vault_forbidden']},confidence:{type:'number',minimum:0,maximum:1},needs_review:{type:'boolean'}},required:['document_type','category','title','summary','search_text','document_date','expiry_date','linked_entity_type','linked_entity_name','parties','tags','sensitivity','confidence','needs_review']};
async function classify(body,user,env){const raw=Uint8Array.from(atob(body.base64||''),c=>c.charCodeAt(0));if(!raw.length)throw new Error('No file content supplied');if(raw.byteLength>10*1024*1024)throw new Error('File is too large for the AI gateway');const form=new FormData();form.append('purpose','user_data');form.append('file',new File([raw],body.name||'document',{type:body.mime||'application/octet-stream'}));const up=await (await openai('/files',env,{method:'POST',body:form})).json();try{const req={model:env.OPENAI_MODEL||'gpt-5.6-luna',store:false,safety_identifier:await safetyId(user.email),reasoning:{effort:'low'},instructions:`You are Private Office's document intelligence engine. Read the supplied file and classify it for a private personal records system. Never copy or expose passwords, OTPs, CVVs, card PINs, transaction PINs, recovery phrases, seed phrases, private keys or authentication codes. If those appear, set sensitivity to vault_forbidden, needs_review to true, and exclude secret values from summary and search_text. Do not invent ownership, dates, people or asset names. search_text should retain useful names, places and non-secret identifiers.`,input:[{role:'user',content:[{type:'input_text',text:`Filename: ${body.name||'document'}\nMIME: ${body.mime||'unknown'}\nReturn structured classification only.`},{type:'input_file',file_id:up.id}]}],text:{format:{type:'json_schema',name:'private_office_document',strict:true,schema},verbosity:'low'}};const d=await (await openai('/responses',env,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req)})).json();return JSON.parse(outputText(d))}finally{try{await openai(`/files/${encodeURIComponent(up.id)}`,env,{method:'DELETE'})}catch{}}}
async function chat(body,user,env){const records=(body.records||[]).slice(0,12).map(r=>({title:r.title,name:r.name,category:r.category,documentType:r.documentType,entityType:r.entityType,entityName:r.entityName,summary:r.summary,searchText:r.searchText,documentDate:r.documentDate,expiryDate:r.expiryDate,drivePath:r.drivePath}));const req={model:env.OPENAI_MODEL||'gpt-5.6-luna',store:false,safety_identifier:await safetyId(user.email),reasoning:{effort:'low'},instructions:`You are Private Office, a discreet private chief of staff. Answer only from the user's supplied indexed record context. Be concise, useful and confident only when the records support it. If the answer is not in the records, say you could not find it and suggest what to index or upload. Never request, reveal, infer or reproduce passwords, PINs, CVVs, OTPs, seed phrases, recovery phrases or private keys. Credential questions belong in the Private Vault.`,input:`USER QUESTION:\n${String(body.message||'').slice(0,4000)}\n\nRELEVANT PRIVATE OFFICE RECORDS:\n${JSON.stringify(records).slice(0,50000)}`};const d=await (await openai('/responses',env,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req)})).json();return outputText(d)||'I could not find a supported answer in the indexed records.'}
export default {async fetch(req,env){const origin=req.headers.get('Origin')||'';if(req.method==='OPTIONS'){if(!originAllowed(origin,env))return new Response(null,{status:403,headers:cors(origin,env)});return new Response(null,{status:204,headers:cors(origin,env)})}if(req.method==='GET')return json({ok:true,service:'Private Office AI Gateway'},200,origin,env);if(req.method!=='POST')return json({error:'Method not allowed'},405,origin,env);if(!originAllowed(origin,env))return json({error:'Origin not allowed'},403,origin,env);try{if(!env.OPENAI_API_KEY||!env.GOOGLE_CLIENT_ID)throw new Error('Gateway secrets are not configured');const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return json({error:'Authentication required'},401,origin,env);const user=await verifyGoogle(auth.slice(7),env);const body=await req.json();if(body.action==='classify')return json({classification:await classify(body,user,env)},200,origin,env);if(body.action==='chat')return json({answer:await chat(body,user,env)},200,origin,env);return json({error:'Unknown action'},400,origin,env)}catch(e){return json({error:e.message||'Gateway error'},500,origin,env)}}};
